### ISSUE TITLE
Problems when applying FOTO package to finer resolution

### ISSUE THREAD

**Issue by vincent-haller** [bluegreen-labs/foto#6]
I am currently using the FOTO index as a predictor variable for biomass in my research, using this package in R. The package does a great job at coarse scales, but when I try to apply it at finer scales it has not been working. I get the following error: "Error in stats::ecdf(i) : 'x' must have 1 or more non-missing values" when using window_size=7, but it works perfectly with window_size=100.

The input tif file is a masked Sentinel 2 NIR product with a resolution of 10m (8 bit unsigned; 11365 columns, 6821 rows). A reference picture is attached (in grey the input tif file, in colour the FOTO index result with window_size=100).
![Sentinel 2 NIR mask Chiloe](https://github.com/bluegreen-labs/foto/assets/124727552/990c91f1-f019-4d31-9529-c7312ee24098)

Is this error produced by a lack of computational capacity? It doesn't seem to be caused by the NA values the tif file has, since it works with a coarser window size.

I am running:
chiloe.S2.NIR.subset <- terra::rast("C:/Users/jvh26/OneDrive - Yale University/MESc Yale/Courses/Research Thesis Project/Data and Data Analysis/Data/FOTO index/FOTO Index Inputs/Chiloe_Sentinel_L2A_B08_NIR_Mosaic_20230217_Quellon.tif")

FOTO.chiloe.S2.NIR <- foto(chiloe.S2.NIR.subset,
     plot = TRUE,
     window_size = 7,         #in pixels
     method = "zones")

**Comment by khufkens** [comment]
You probably have NA values in your map. As such it is non continuous when you decrease the window size (all values are NA). Now, this scenario is a bit tricky anyway as edge cases will happen.

For now I would fill the NA values in your map with something out of the normal range of your data (e.g. -9999). Then run the analysis on a window size of 7. After this analysis for every 7x7 pixel  window determine the fraction of -9999 pixels and mask anything which isn't 100% true data.

**Comment by khufkens** [comment]
Address in future release:
https://github.com/bluegreen-labs/foto/issues/7

**Comment by khufkens** [comment]
@vincent-haller Would it be possible to share a small subset of the data to debug on?

**Comment by vincent-haller** [comment]
Thank you for your help! The original dataset and subset of it is available here: https://drive.google.com/drive/folders/1NfaRou_Xa2KGrrc4LS1NzrrW5AzpSdJB?usp=sharing 

Inspecting the attached image, there probably are windows in which all values are NA for the output with a window_size=100 (for example in the right middle area), which makes me question whether that is the problem for window_size=7. Would love to hear your thoughts on this.

**Comment by khufkens** [comment]
Oh, I just realized why this doesn't work. Stupid me. Brain is in fritz tonight.

So, the algorithm detects texture based upon what it measures within the context of your moving window. When this window becomes too small you don't have enough information for a meaningful texture analysis (which returns results, but messes with the plotting routine).

The only way to bump up the coverage spatially (not having these chunky zones) is to use a moving window approach (method = "mw"). You then need to tailor your desired scope of the analysis (window size) to what is reasonable (what is roughly expected as a maximum crown size x 5-10).

**Comment by vincent-haller** [comment]
I run into that problem in an earlier analysis, using window_size=3. But window_size=7 (which means 70 meters, equivalent to 7 pixels of 10m in the Sentinel product) worked in a subset of data. The results are attached:

![FOTO Outcome NIR Yaldad](https://github.com/bluegreen-labs/foto/assets/124727552/fca41275-7355-48c9-874b-f6958374fc58)

Original datasets (input and output) are available here: https://drive.google.com/drive/folders/1ZpadQim5KrHADdiwfbnQFcVwGqXS54Od?usp=sharing 

Therefore, I would think it is possible to use window_size=7. Would there be any other possible explanation on why it does not work on a larger area?

**Comment by khufkens** [comment]
The algorithm works as follows:

You take a YxY window, and apply a Fourier transform (FFT). This captures the frequency and phase of the 2D signal in this window. You average the frequency component, folding the 2D response into a 1D signal, by radial averaging. This remaining signal is used as a feature vector (input) to a PCA analysis. From this the first 3 PC are retained.

The smaller the window, the less the FFT will have contextual (texture) meaning. You need spatial context for this analysis to function correctly. So although there is output, I don't think the signal represents what you think it does.

This is an intro in FFT image manipulation in the frequency domain.
https://www.youtube.com/watch?v=OOu5KP3Gvx0

Let me  know if you have any more questions. I'll try to write this up in a blog post as the context is rather interesting for teaching purposes.

**Comment by khufkens** [comment]
Hi @vincent-haller basically anything under a window size of 7 isn't really feasible. So, I've relaxed the constraints on the harmonics. By default there are 29 considered, and there are no low level cut-offs anymore (which was the potential cause of your issue). For this feature install the latest github release v1.2.

```r
library(terra)
library(foto)

r <- rast("Chiloe_Sentinel_L2A_B08_NIR_Mosaic_20230217_Quellon_subset.tif")
f <- foto(r, window_size = 7, plot = TRUE)
```

**Comment by khufkens** [comment]
Note, the harmonics for these smaller window sizes are of less value (as mentioned before, caveats apply for these and it is best to match the textures scale combined with a reasonable window size). If you need to increase the spatial resolution you will want to use the moving window approach rather than decrease the size of the window!!!

**Comment by vincent-haller** [comment]
Hi Koen,

Thank you so much for the explanations and updates! I ran the FOTO index with a window size of 10 and it worked. I might try the WS of 7 in the new version later on if the correlation to biomass with current outputs is low. I can report back on how it goes. 

Additional comment in case it is of your interest: In my case (Sentinel 2 NIR 10m), the PC2 seems to be capturing the canopy size variability and PC1 takes over to topographical variability, probably due to the hilly topography of my particular study area. Therefore, the selection of the PC to be used as predictor for biomass needs to be done cautiously.

**Comment by vincent-haller** [comment]
One final question: would you recommend using the norm_spec and high_pass options of the foto function for modelling biomass? Where can I read more about what this exactly does to the output?
Thank you again for all the support!

**Comment by khufkens** [comment]
Hi Vincent, notes of caution here - especially when generalizing statements. PC loadings will probably be dependent on the regional dynamics, the methods used (i.e. a high pass filter removes much of this slow varying component from the data) etc.

I will probably also add an additional option in the circular averaging, using either rounded (integer) or floating point values. The latter inflates the number of features, while the former averages signals more. There is no good or bad in this, but something to be aware of. Currently the data is not rounded to the nearest integer (of a harmonic) - see demo vignette.

Please do report back with some examples as it is nice to have true data to see it executed on.
